remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: "Ucrypt-TS"
description: "A simple cryptographic library for secure data handling."
lsi: false
safe: true
source: "."
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge